Set Shell zsh

Output "./img/demo-sequence.gif"

Set FontSize 11
Set Width 800
Set Height 400
Set Padding 15
Set WindowBar Colorful
Set Theme "nord"

Hide

Env SAUVA_CONFIG_FILE "./img/config.toml"
Type "cargo run --release -- --graphics iterm2 --text 'Šaúvá❤️‍🔥'"
Enter
Sleep 2s

Show

# Sequence

Sleep 2s

Type@300ms "jjjjjj"
Sleep 500ms

Type "n"
Sleep 1s

# Normalization

Type@500ms "jjj"
Sleep 500ms

Screenshot "./img/sequence-normalization.png"
Sleep 100ms

Enter
Sleep 1s

# Normalization result

Type@300ms "jjj"

Screenshot "./img/sequence-normalization-result.png"
Sleep 100ms

Type@300ms "jjjjj"
Sleep 1s

Type "Y"
Sleep 1s

Screenshot "./img/sequence-normalization-result-copy.png"
Sleep 100ms

Type "j"
Sleep 500ms

Enter
Sleep 1s

Backspace
Sleep 500ms
Backspace
Sleep 1s

# Sequence

Type "Y"
Sleep 1s

Screenshot "./img/sequence-copy.png"
Sleep 100ms

Type@300ms "jjj"
Sleep 500ms

Escape
Sleep 500ms

Type@300ms "jjj"
Sleep 500ms

Screenshot "./img/sequence.png"
Sleep 100ms

Enter

Screenshot "./img/sequence-inspector.png"
Sleep 100ms

Sleep 2s
