Set Shell zsh

Output "./img/demo-sequence.gif"

Set FontSize 11
Set Width 800
Set Height 400
Set Padding 15
Set WindowBar Colorful
Set Theme "nord"

Hide

Env SAUVA_CONFIG_FILE "./img/config.toml"
Type "cargo run --release -- --graphics iterm2 --text 'sauva❤️‍🔥'"
Enter
Sleep 2s

Show

Sleep 2s

Type@300ms "jjjjjjjj"
Sleep 500ms

Screenshot "./img/sequence.png"
Sleep 100ms

Enter
Sleep 1s

Screenshot "./img/inspector-sequence.png"
Sleep 100ms

Backspace
Sleep 500ms

Type "k"

Sleep 2s
